### ISSUE TITLE
Update 1.16 branch

### ISSUE THREAD

**Issue by ravenbuilder934** [ochotonida/bones#4]
Hi, I'd like to make a pull request to update Bones from 1.16.1 to 1.16.5. However, it seems like the 1.16 branch is the same as the 1.15 branch. Could you please update the 1.16 branch to match the latest 1.16.1 file?

**Comment by ochotonida** [comment]
It seems I forgot to push to github when I initially ported to 1.16, and then deleted my local repository some time after under the assumption that I had a backup. 
Because of that, I've simply gone ahead and ported from 1.15 straight to 1.16.5. The code could still use some work, and I'm still not entirely happy with the current state of the mod (the main reason I've been putting off porting it for so long), but since I'm a bit short on time at the moment, I figured I'd just leave it as is for now.
I've released a beta on curseforge for the time being, and the 1.16 branch is now up-to-date.

**Comment by ravenbuilder934** [comment]
Okay, thank you!
